export interface Country {
  isoCode: string;
  name: string;
  iso3Code: string;
  flag: string;
  dial: string;
  currency: string;
  capital: string;
  continent: string;
  phoneCode: string;
}

export const countryList: Country[] = [
  {
    isoCode: 'US',
    name: 'United States',
    iso3Code: 'USA',
    flag: '🇺🇸',
    dial: '1',
    currency: 'USD',
    capital: 'Washington',
    continent: 'NA',
    phoneCode: '1',
  },
  {
    isoCode: 'VN',
    name: 'Viet Nam',
    iso3Code: 'VNM',
    flag: '🇻🇳',
    dial: '84',
    currency: 'VND',
    capital: 'Hanoi',
    continent: 'AS',
    phoneCode: '84',
  },
  {
    isoCode: 'BD',
    name: 'Bangladesh',
    iso3Code: 'BGD',
    flag: '🇧🇩',
    dial: '880',
    currency: 'BDT',
    capital: 'Dhaka',
    continent: 'AS',
    phoneCode: '880',
  },
  {
    isoCode: 'BE',
    name: 'Belgium',
    iso3Code: 'BEL',
    flag: '🇧🇪',
    dial: '32',
    currency: 'EUR',
    capital: 'Brussels',
    continent: 'EU',
    phoneCode: '32',
  },
  {
    isoCode: 'BF',
    name: 'Burkina Faso',
    iso3Code: 'BFA',
    flag: '🇧🇫',
    dial: '226',
    currency: 'XOF',
    capital: 'Ouagadougou',
    continent: 'AF',
    phoneCode: '226',
  },
  {
    isoCode: 'BG',
    name: 'Bulgaria',
    iso3Code: 'BGR',
    flag: '🇧🇬',
    dial: '359',
    currency: 'BGN',
    capital: 'Sofia',
    continent: 'EU',
    phoneCode: '359',
  },
  {
    isoCode: 'BA',
    name: 'Bosnia and Herzegovina',
    iso3Code: 'BIH',
    flag: '🇧🇦',
    dial: '387',
    currency: 'BAM',
    capital: 'Sarajevo',
    continent: 'EU',
    phoneCode: '387',
  },
  {
    isoCode: 'BB',
    name: 'Barbados',
    iso3Code: 'BRB',
    flag: '🇧🇧',
    dial: '1-246',
    currency: 'BBD',
    capital: 'Bridgetown',
    continent: 'NA',
    phoneCode: '1-246',
  },
  {
    isoCode: 'WF',
    name: 'Wallis and Futuna',
    iso3Code: 'WLF',
    flag: '🇼🇫',
    dial: '681',
    currency: 'XPF',
    capital: 'Mata Utu',
    continent: 'OC',
    phoneCode: '681',
  },
  {
    isoCode: 'BL',
    name: 'Saint Barthelemy',
    iso3Code: 'BLM',
    flag: '🇧🇱',
    dial: '590',
    currency: 'EUR',
    capital: 'Gustavia',
    continent: 'NA',
    phoneCode: '590',
  },
  {
    isoCode: 'BM',
    name: 'Bermuda',
    iso3Code: 'BMU',
    flag: '🇧🇲',
    dial: '1-441',
    currency: 'BMD',
    capital: 'Hamilton',
    continent: 'NA',
    phoneCode: '1-441',
  },
  {
    isoCode: 'BN',
    name: 'Brunei',
    iso3Code: 'BRN',
    flag: '🇧🇳',
    dial: '673',
    currency: 'BND',
    capital: 'Bandar Seri Begawan',
    continent: 'AS',
    phoneCode: '673',
  },
  {
    isoCode: 'BO',
    name: 'Bolivia',
    iso3Code: 'BOL',
    flag: '🇧🇴',
    dial: '591',
    currency: 'BOB',
    capital: 'Sucre',
    continent: 'SA',
    phoneCode: '591',
  },
  {
    isoCode: 'BH',
    name: 'Bahrain',
    iso3Code: 'BHR',
    flag: '🇧🇭',
    dial: '973',
    currency: 'BHD',
    capital: 'Manama',
    continent: 'AS',
    phoneCode: '973',
  },
  {
    isoCode: 'BI',
    name: 'Burundi',
    iso3Code: 'BDI',
    flag: '🇧🇮',
    dial: '257',
    currency: 'BIF',
    capital: 'Bujumbura',
    continent: 'AF',
    phoneCode: '257',
  },
  {
    isoCode: 'BJ',
    name: 'Benin',
    iso3Code: 'BEN',
    flag: '🇧🇯',
    dial: '229',
    currency: 'XOF',
    capital: 'Porto-Novo',
    continent: 'AF',
    phoneCode: '229',
  },
  {
    isoCode: 'BT',
    name: 'Bhutan',
    iso3Code: 'BTN',
    flag: '🇧🇹',
    dial: '975',
    currency: 'BTN',
    capital: 'Thimphu',
    continent: 'AS',
    phoneCode: '975',
  },
  {
    isoCode: 'JM',
    name: 'Jamaica',
    iso3Code: 'JAM',
    flag: '🇯🇲',
    dial: '1-876',
    currency: 'JMD',
    capital: 'Kingston',
    continent: 'NA',
    phoneCode: '1-876',
  },
  {
    isoCode: 'BV',
    name: 'Bouvet Island',
    iso3Code: 'BVT',
    flag: '🇧🇻',
    dial: '47',
    currency: 'NOK',
    capital: '',
    continent: 'AN',
    phoneCode: '47',
  },
  {
    isoCode: 'BW',
    name: 'Botswana',
    iso3Code: 'BWA',
    flag: '🇧🇼',
    dial: '267',
    currency: 'BWP',
    capital: 'Gaborone',
    continent: 'AF',
    phoneCode: '267',
  },
  {
    isoCode: 'WS',
    name: 'Samoa',
    iso3Code: 'WSM',
    flag: '🇼🇸',
    dial: '685',
    currency: 'WST',
    capital: 'Apia',
    continent: 'OC',
    phoneCode: '685',
  },
  {
    isoCode: 'BQ',
    name: 'Bonaire, Saint Eustatius and Saba ',
    iso3Code: 'BES',
    flag: '🇧🇶',
    dial: '599',
    currency: 'USD',
    capital: '',
    continent: 'NA',
    phoneCode: '599',
  },
  {
    isoCode: 'BR',
    name: 'Brazil',
    iso3Code: 'BRA',
    flag: '🇧🇷',
    dial: '55',
    currency: 'BRL',
    capital: 'Brasilia',
    continent: 'SA',
    phoneCode: '55',
  },
  {
    isoCode: 'BS',
    name: 'Bahamas',
    iso3Code: 'BHS',
    flag: '🇧🇸',
    dial: '1242',
    currency: 'BSD',
    capital: 'Nassau',
    continent: 'NA',
    phoneCode: '1242',
  },
  {
    isoCode: 'JE',
    name: 'Jersey',
    iso3Code: 'JEY',
    flag: '🇯🇪',
    dial: '44',
    currency: 'GBP',
    capital: 'Saint Helier',
    continent: 'EU',
    phoneCode: '44-1534',
  },
  {
    isoCode: 'BY',
    name: 'Belarus',
    iso3Code: 'BLR',
    flag: '🇧🇾',
    dial: '375',
    currency: 'BYR',
    capital: 'Minsk',
    continent: 'EU',
    phoneCode: '375',
  },
  {
    isoCode: 'BZ',
    name: 'Belize',
    iso3Code: 'BLZ',
    flag: '🇧🇿',
    dial: '501',
    currency: 'BZD',
    capital: 'Belmopan',
    continent: 'NA',
    phoneCode: '501',
  },
  {
    isoCode: 'RU',
    name: 'Russia',
    iso3Code: 'RUS',
    flag: '🇷🇺',
    dial: '7',
    currency: 'RUB',
    capital: 'Moscow',
    continent: 'EU',
    phoneCode: '7',
  },
  {
    isoCode: 'RW',
    name: 'Rwanda',
    iso3Code: 'RWA',
    flag: '🇷🇼',
    dial: '250',
    currency: 'RWF',
    capital: 'Kigali',
    continent: 'AF',
    phoneCode: '250',
  },
  {
    isoCode: 'RS',
    name: 'Serbia',
    iso3Code: 'SRB',
    flag: '🇷🇸',
    dial: '381',
    currency: 'RSD',
    capital: 'Belgrade',
    continent: 'EU',
    phoneCode: '381',
  },
  {
    isoCode: 'TL',
    name: 'East Timor',
    iso3Code: 'TLS',
    flag: '🇹🇱',
    dial: '670',
    currency: 'USD',
    capital: 'Dili',
    continent: 'OC',
    phoneCode: '670',
  },
  {
    isoCode: 'RE',
    name: 'Reunion',
    iso3Code: 'REU',
    flag: '🇷🇪',
    dial: '262',
    currency: 'EUR',
    capital: 'Saint-Denis',
    continent: 'AF',
    phoneCode: '262',
  },
  {
    isoCode: 'TM',
    name: 'Turkmenistan',
    iso3Code: 'TKM',
    flag: '🇹🇲',
    dial: '993',
    currency: 'TMT',
    capital: 'Ashgabat',
    continent: 'AS',
    phoneCode: '993',
  },
  {
    isoCode: 'TJ',
    name: 'Tajikistan',
    iso3Code: 'TJK',
    flag: '🇹🇯',
    dial: '992',
    currency: 'TJS',
    capital: 'Dushanbe',
    continent: 'AS',
    phoneCode: '992',
  },
  {
    isoCode: 'RO',
    name: 'Romania',
    iso3Code: 'ROU',
    flag: '🇷🇴',
    dial: '40',
    currency: 'RON',
    capital: 'Bucharest',
    continent: 'EU',
    phoneCode: '40',
  },
  {
    isoCode: 'TK',
    name: 'Tokelau',
    iso3Code: 'TKL',
    flag: '🇹🇰',
    dial: '690',
    currency: 'NZD',
    capital: '',
    continent: 'OC',
    phoneCode: '690',
  },
  {
    isoCode: 'GW',
    name: 'Guinea-Bissau',
    iso3Code: 'GNB',
    flag: '🇬🇼',
    dial: '245',
    currency: 'XOF',
    capital: 'Bissau',
    continent: 'AF',
    phoneCode: '245',
  },
  {
    isoCode: 'GU',
    name: 'Guam',
    iso3Code: 'GUM',
    flag: '🇬🇺',
    dial: '1-671',
    currency: 'USD',
    capital: 'Hagatna',
    continent: 'OC',
    phoneCode: '1-671',
  },
  {
    isoCode: 'GT',
    name: 'Guatemala',
    iso3Code: 'GTM',
    flag: '🇬🇹',
    dial: '502',
    currency: 'GTQ',
    capital: 'Guatemala City',
    continent: 'NA',
    phoneCode: '502',
  },
  {
    isoCode: 'GS',
    name: 'South Georgia and the South Sandwich Islands',
    iso3Code: 'SGS',
    flag: '🇬🇸',
    dial: '500',
    currency: 'GBP',
    capital: 'Grytviken',
    continent: 'AN',
    phoneCode: '500',
  },
  {
    isoCode: 'GR',
    name: 'Greece',
    iso3Code: 'GRC',
    flag: '🇬🇷',
    dial: '30',
    currency: 'EUR',
    capital: 'Athens',
    continent: 'EU',
    phoneCode: '30',
  },
  {
    isoCode: 'GQ',
    name: 'Equatorial Guinea',
    iso3Code: 'GNQ',
    flag: '🇬🇶',
    dial: '240',
    currency: 'XAF',
    capital: 'Malabo',
    continent: 'AF',
    phoneCode: '240',
  },
  {
    isoCode: 'GP',
    name: 'Guadeloupe',
    iso3Code: 'GLP',
    flag: '🇬🇵',
    dial: '590',
    currency: 'EUR',
    capital: 'Basse-Terre',
    continent: 'NA',
    phoneCode: '590',
  },
  {
    isoCode: 'JP',
    name: 'Japan',
    iso3Code: 'JPN',
    flag: '🇯🇵',
    dial: '81',
    currency: 'JPY',
    capital: 'Tokyo',
    continent: 'AS',
    phoneCode: '81',
  },
  {
    isoCode: 'GY',
    name: 'Guyana',
    iso3Code: 'GUY',
    flag: '🇬🇾',
    dial: '592',
    currency: 'GYD',
    capital: 'Georgetown',
    continent: 'SA',
    phoneCode: '592',
  },
  {
    isoCode: 'GG',
    name: 'Guernsey',
    iso3Code: 'GGY',
    flag: '🇬🇬',
    dial: '44-1481',
    currency: 'GBP',
    capital: 'St Peter Port',
    continent: 'EU',
    phoneCode: '44-1481',
  },
  {
    isoCode: 'GF',
    name: 'French Guiana',
    iso3Code: 'GUF',
    flag: '🇬🇫',
    dial: '594',
    currency: 'EUR',
    capital: 'Cayenne',
    continent: 'SA',
    phoneCode: '594',
  },
  {
    isoCode: 'GE',
    name: 'Georgia',
    iso3Code: 'GEO',
    flag: '🇬🇪',
    dial: '995',
    currency: 'GEL',
    capital: 'Tbilisi',
    continent: 'AS',
    phoneCode: '995',
  },
  {
    isoCode: 'GD',
    name: 'Grenada',
    iso3Code: 'GRD',
    flag: '🇬🇩',
    dial: '1-473',
    currency: 'XCD',
    capital: "St. George's",
    continent: 'NA',
    phoneCode: '1-473',
  },
  {
    isoCode: 'GB',
    name: 'United Kingdom',
    iso3Code: 'GBR',
    flag: '🇬🇧',
    dial: '44',
    currency: 'GBP',
    capital: 'London',
    continent: 'EU',
    phoneCode: '44',
  },
  {
    isoCode: 'GA',
    name: 'Gabon',
    iso3Code: 'GAB',
    flag: '🇬🇦',
    dial: '241',
    currency: 'XAF',
    capital: 'Libreville',
    continent: 'AF',
    phoneCode: '241',
  },
  {
    isoCode: 'SV',
    name: 'El Salvador',
    iso3Code: 'SLV',
    flag: '🇸🇻',
    dial: '503',
    currency: 'USD',
    capital: 'San Salvador',
    continent: 'NA',
    phoneCode: '503',
  },
  {
    isoCode: 'GN',
    name: 'Guinea',
    iso3Code: 'GIN',
    flag: '🇬🇳',
    dial: '224',
    currency: 'GNF',
    capital: 'Conakry',
    continent: 'AF',
    phoneCode: '224',
  },
  {
    isoCode: 'GM',
    name: 'Gambia',
    iso3Code: 'GMB',
    flag: '🇬🇲',
    dial: '220',
    currency: 'GMD',
    capital: 'Banjul',
    continent: 'AF',
    phoneCode: '220',
  },
  {
    isoCode: 'GL',
    name: 'Greenland',
    iso3Code: 'GRL',
    flag: '🇬🇱',
    dial: '299',
    currency: 'DKK',
    capital: 'Nuuk',
    continent: 'NA',
    phoneCode: '299',
  },
  {
    isoCode: 'GI',
    name: 'Gibraltar',
    iso3Code: 'GIB',
    flag: '🇬🇮',
    dial: '350',
    currency: 'GIP',
    capital: 'Gibraltar',
    continent: 'EU',
    phoneCode: '350',
  },
  {
    isoCode: 'GH',
    name: 'Ghana',
    iso3Code: 'GHA',
    flag: '🇬🇭',
    dial: '233',
    currency: 'GHS',
    capital: 'Accra',
    continent: 'AF',
    phoneCode: '233',
  },
  {
    isoCode: 'OM',
    name: 'Oman',
    iso3Code: 'OMN',
    flag: '🇴🇲',
    dial: '968',
    currency: 'OMR',
    capital: 'Muscat',
    continent: 'AS',
    phoneCode: '968',
  },
  {
    isoCode: 'TN',
    name: 'Tunisia',
    iso3Code: 'TUN',
    flag: '🇹🇳',
    dial: '216',
    currency: 'TND',
    capital: 'Tunis',
    continent: 'AF',
    phoneCode: '216',
  },
  {
    isoCode: 'JO',
    name: 'Jordan',
    iso3Code: 'JOR',
    flag: '🇯🇴',
    dial: '962',
    currency: 'JOD',
    capital: 'Amman',
    continent: 'AS',
    phoneCode: '962',
  },
  {
    isoCode: 'HR',
    name: 'Croatia',
    iso3Code: 'HRV',
    flag: '🇭🇷',
    dial: '385',
    currency: 'HRK',
    capital: 'Zagreb',
    continent: 'EU',
    phoneCode: '385',
  },
  {
    isoCode: 'HT',
    name: 'Haiti',
    iso3Code: 'HTI',
    flag: '🇭🇹',
    dial: '509',
    currency: 'HTG',
    capital: 'Port-au-Prince',
    continent: 'NA',
    phoneCode: '509',
  },
  {
    isoCode: 'HU',
    name: 'Hungary',
    iso3Code: 'HUN',
    flag: '🇭🇺',
    dial: '36',
    currency: 'HUF',
    capital: 'Budapest',
    continent: 'EU',
    phoneCode: '36',
  },
  {
    isoCode: 'HK',
    name: 'Hong Kong',
    iso3Code: 'HKG',
    flag: '🇭🇰',
    dial: '852',
    currency: 'HKD',
    capital: 'Hong Kong',
    continent: 'AS',
    phoneCode: '852',
  },
  {
    isoCode: 'HN',
    name: 'Honduras',
    iso3Code: 'HND',
    flag: '🇭🇳',
    dial: '504',
    currency: 'HNL',
    capital: 'Tegucigalpa',
    continent: 'NA',
    phoneCode: '504',
  },
  {
    isoCode: 'HM',
    name: 'Heard Island and McDonald Islands',
    iso3Code: 'HMD',
    flag: '🇭🇲',
    dial: '672',
    currency: 'AUD',
    capital: '',
    continent: 'AN',
    phoneCode: '672',
  },
  {
    isoCode: 'VE',
    name: 'Venezuela',
    iso3Code: 'VEN',
    flag: '🇻🇪',
    dial: '58',
    currency: 'VEF',
    capital: 'Caracas',
    continent: 'SA',
    phoneCode: '58',
  },
  {
    isoCode: 'PR',
    name: 'Puerto Rico',
    iso3Code: 'PRI',
    flag: '🇵🇷',
    dial: '1-787',
    currency: 'USD',
    capital: 'San Juan',
    continent: 'NA',
    phoneCode: '1-787',
  },

  {
    isoCode: 'PS',
    name: 'Palestinian Territory',
    iso3Code: 'PSE',
    flag: '🇵🇸',
    dial: '970',
    currency: 'ILS',
    capital: 'East Jerusalem',
    continent: 'AS',
    phoneCode: '970',
  },
  {
    isoCode: 'PW',
    name: 'Palau',
    iso3Code: 'PLW',
    flag: '🇵🇼',
    dial: '680',
    currency: 'USD',
    capital: 'Melekeok',
    continent: 'OC',
    phoneCode: '680',
  },
  {
    isoCode: 'PT',
    name: 'Portugal',
    iso3Code: 'PRT',
    flag: '🇵🇹',
    dial: '351',
    currency: 'EUR',
    capital: 'Lisbon',
    continent: 'EU',
    phoneCode: '351',
  },
  {
    isoCode: 'SJ',
    name: 'Svalbard and Jan Mayen',
    iso3Code: 'SJM',
    flag: '🇸🇯',
    dial: '47',
    currency: 'NOK',
    capital: 'Longyearbyen',
    continent: 'EU',
    phoneCode: '47',
  },
  {
    isoCode: 'PY',
    name: 'Paraguay',
    iso3Code: 'PRY',
    flag: '🇵🇾',
    dial: '595',
    currency: 'PYG',
    capital: 'Asuncion',
    continent: 'SA',
    phoneCode: '595',
  },
  {
    isoCode: 'IQ',
    name: 'Iraq',
    iso3Code: 'IRQ',
    flag: '🇮🇶',
    dial: '964',
    currency: 'IQD',
    capital: 'Baghdad',
    continent: 'AS',
    phoneCode: '964',
  },
  {
    isoCode: 'PA',
    name: 'Panama',
    iso3Code: 'PAN',
    flag: '🇵🇦',
    dial: '507',
    currency: 'PAB',
    capital: 'Panama City',
    continent: 'NA',
    phoneCode: '507',
  },
  {
    isoCode: 'PF',
    name: 'French Polynesia',
    iso3Code: 'PYF',
    flag: '🇵🇫',
    dial: '689',
    currency: 'XPF',
    capital: 'Papeete',
    continent: 'OC',
    phoneCode: '689',
  },
  {
    isoCode: 'PG',
    name: 'Papua New Guinea',
    iso3Code: 'PNG',
    flag: '🇵🇬',
    dial: '675',
    currency: 'PGK',
    capital: 'Port Moresby',
    continent: 'OC',
    phoneCode: '675',
  },
  {
    isoCode: 'PE',
    name: 'Peru',
    iso3Code: 'PER',
    flag: '🇵🇪',
    dial: '51',
    currency: 'PEN',
    capital: 'Lima',
    continent: 'SA',
    phoneCode: '51',
  },
  {
    isoCode: 'PK',
    name: 'Pakistan',
    iso3Code: 'PAK',
    flag: '🇵🇰',
    dial: '92',
    currency: 'PKR',
    capital: 'Islamabad',
    continent: 'AS',
    phoneCode: '92',
  },
  {
    isoCode: 'PH',
    name: 'Philippines',
    iso3Code: 'PHL',
    flag: '🇵🇭',
    dial: '63',
    currency: 'PHP',
    capital: 'Manila',
    continent: 'AS',
    phoneCode: '63',
  },
  {
    isoCode: 'PN',
    name: 'Pitcairn',
    iso3Code: 'PCN',
    flag: '🇵🇳',
    dial: '870',
    currency: 'NZD',
    capital: 'Adamstown',
    continent: 'OC',
    phoneCode: '870',
  },
  {
    isoCode: 'PL',
    name: 'Poland',
    iso3Code: 'POL',
    flag: '🇵🇱',
    dial: '48',
    currency: 'PLN',
    capital: 'Warsaw',
    continent: 'EU',
    phoneCode: '48',
  },
  {
    isoCode: 'PM',
    name: 'Saint Pierre and Miquelon',
    iso3Code: 'SPM',
    flag: '🇵🇲',
    dial: '508',
    currency: 'EUR',
    capital: 'Saint-Pierre',
    continent: 'NA',
    phoneCode: '508',
  },
  {
    isoCode: 'ZM',
    name: 'Zambia',
    iso3Code: 'ZMB',
    flag: '🇿🇲',
    dial: '260',
    currency: 'ZMK',
    capital: 'Lusaka',
    continent: 'AF',
    phoneCode: '260',
  },
  {
    isoCode: 'EH',
    name: 'Western Sahara',
    iso3Code: 'ESH',
    flag: '🇪🇭',
    dial: '212',
    currency: 'MAD',
    capital: 'El-Aaiun',
    continent: 'AF',
    phoneCode: '212',
  },
  {
    isoCode: 'EE',
    name: 'Estonia',
    iso3Code: 'EST',
    flag: '🇪🇪',
    dial: '372',
    currency: 'EUR',
    capital: 'Tallinn',
    continent: 'EU',
    phoneCode: '372',
  },
  {
    isoCode: 'EG',
    name: 'Egypt',
    iso3Code: 'EGY',
    flag: '🇪🇬',
    dial: '20',
    currency: 'EGP',
    capital: 'Cairo',
    continent: 'AF',
    phoneCode: '20',
  },
  {
    isoCode: 'ZA',
    name: 'South Africa',
    iso3Code: 'ZAF',
    flag: '🇿🇦',
    dial: '27',
    currency: 'ZAR',
    capital: 'Pretoria',
    continent: 'AF',
    phoneCode: '27',
  },
  {
    isoCode: 'EC',
    name: 'Ecuador',
    iso3Code: 'ECU',
    flag: '🇪🇨',
    dial: '593',
    currency: 'USD',
    capital: 'Quito',
    continent: 'SA',
    phoneCode: '593',
  },
  {
    isoCode: 'IT',
    name: 'Italy',
    iso3Code: 'ITA',
    flag: '🇮🇹',
    dial: '39',
    currency: 'EUR',
    capital: 'Rome',
    continent: 'EU',
    phoneCode: '39',
  },
  {
    isoCode: 'SB',
    name: 'Solomon Islands',
    iso3Code: 'SLB',
    flag: '🇸🇧',
    dial: '677',
    currency: 'SBD',
    capital: 'Honiara',
    continent: 'OC',
    phoneCode: '677',
  },
  {
    isoCode: 'ET',
    name: 'Ethiopia',
    iso3Code: 'ETH',
    flag: '🇪🇹',
    dial: '251',
    currency: 'ETB',
    capital: 'Addis Ababa',
    continent: 'AF',
    phoneCode: '251',
  },
  {
    isoCode: 'SO',
    name: 'Somalia',
    iso3Code: 'SOM',
    flag: '🇸🇴',
    dial: '252',
    currency: 'SOS',
    capital: 'Mogadishu',
    continent: 'AF',
    phoneCode: '252',
  },
  {
    isoCode: 'ZW',
    name: 'Zimbabwe',
    iso3Code: 'ZWE',
    flag: '🇿🇼',
    dial: '263',
    currency: 'ZWL',
    capital: 'Harare',
    continent: 'AF',
    phoneCode: '263',
  },
  {
    isoCode: 'SA',
    name: 'Saudi Arabia',
    iso3Code: 'SAU',
    flag: '🇸🇦',
    dial: '966',
    currency: 'SAR',
    capital: 'Riyadh',
    continent: 'AS',
    phoneCode: '966',
  },
  {
    isoCode: 'ES',
    name: 'Spain',
    iso3Code: 'ESP',
    flag: '🇪🇸',
    dial: '34',
    currency: 'EUR',
    capital: 'Madrid',
    continent: 'EU',
    phoneCode: '34',
  },
  {
    isoCode: 'ER',
    name: 'Eritrea',
    iso3Code: 'ERI',
    flag: '🇪🇷',
    dial: '291',
    currency: 'ERN',
    capital: 'Asmara',
    continent: 'AF',
    phoneCode: '291',
  },
  {
    isoCode: 'ME',
    name: 'Montenegro',
    iso3Code: 'MNE',
    flag: '🇲🇪',
    dial: '382',
    currency: 'EUR',
    capital: 'Podgorica',
    continent: 'EU',
    phoneCode: '382',
  },
  {
    isoCode: 'MD',
    name: 'Moldova',
    iso3Code: 'MDA',
    flag: '🇲🇩',
    dial: '373',
    currency: 'MDL',
    capital: 'Chisinau',
    continent: 'EU',
    phoneCode: '373',
  },
  {
    isoCode: 'MG',
    name: 'Madagascar',
    iso3Code: 'MDG',
    flag: '🇲🇬',
    dial: '261',
    currency: 'MGA',
    capital: 'Antananarivo',
    continent: 'AF',
    phoneCode: '261',
  },
  {
    isoCode: 'MF',
    name: 'Saint Martin',
    iso3Code: 'MAF',
    flag: '🇲🇫',
    dial: '590',
    currency: 'EUR',
    capital: 'Marigot',
    continent: 'NA',
    phoneCode: '590',
  },
  {
    isoCode: 'MA',
    name: 'Morocco',
    iso3Code: 'MAR',
    flag: '🇲🇦',
    dial: '212',
    currency: 'MAD',
    capital: 'Rabat',
    continent: 'AF',
    phoneCode: '212',
  },
  {
    isoCode: 'MC',
    name: 'Monaco',
    iso3Code: 'MCO',
    flag: '🇲🇨',
    dial: '377',
    currency: 'EUR',
    capital: 'Monaco',
    continent: 'EU',
    phoneCode: '377',
  },
  {
    isoCode: 'UZ',
    name: 'Uzbekistan',
    iso3Code: 'UZB',
    flag: '🇺🇿',
    dial: '998',
    currency: 'UZS',
    capital: 'Tashkent',
    continent: 'AS',
    phoneCode: '998',
  },
  {
    isoCode: 'MM',
    name: 'Myanmar',
    iso3Code: 'MMR',
    flag: '🇲🇲',
    dial: '95',
    currency: 'MMK',
    capital: 'Nay Pyi Taw',
    continent: 'AS',
    phoneCode: '95',
  },
  {
    isoCode: 'ML',
    name: 'Mali',
    iso3Code: 'MLI',
    flag: '🇲🇱',
    dial: '223',
    currency: 'XOF',
    capital: 'Bamako',
    continent: 'AF',
    phoneCode: '223',
  },
  {
    isoCode: 'MO',
    name: 'Macao',
    iso3Code: 'MAC',
    flag: '🇲🇴',
    dial: '853',
    currency: 'MOP',
    capital: 'Macao',
    continent: 'AS',
    phoneCode: '853',
  },
  {
    isoCode: 'MN',
    name: 'Mongolia',
    iso3Code: 'MNG',
    flag: '🇲🇳',
    dial: '976',
    currency: 'MNT',
    capital: 'Ulan Bator',
    continent: 'AS',
    phoneCode: '976',
  },
  {
    isoCode: 'MH',
    name: 'Marshall Islands',
    iso3Code: 'MHL',
    flag: '🇲🇭',
    dial: '692',
    currency: 'USD',
    capital: 'Majuro',
    continent: 'OC',
    phoneCode: '692',
  },
  {
    isoCode: 'MK',
    name: 'Macedonia',
    iso3Code: 'MKD',
    flag: '🇲🇰',
    dial: '389',
    currency: 'MKD',
    capital: 'Skopje',
    continent: 'EU',
    phoneCode: '389',
  },
  {
    isoCode: 'MU',
    name: 'Mauritius',
    iso3Code: 'MUS',
    flag: '🇲🇺',
    dial: '230',
    currency: 'MUR',
    capital: 'Port Louis',
    continent: 'AF',
    phoneCode: '230',
  },
  {
    isoCode: 'MT',
    name: 'Malta',
    iso3Code: 'MLT',
    flag: '🇲🇹',
    dial: '356',
    currency: 'EUR',
    capital: 'Valletta',
    continent: 'EU',
    phoneCode: '356',
  },
  {
    isoCode: 'MW',
    name: 'Malawi',
    iso3Code: 'MWI',
    flag: '🇲🇼',
    dial: '265',
    currency: 'MWK',
    capital: 'Lilongwe',
    continent: 'AF',
    phoneCode: '265',
  },
  {
    isoCode: 'MV',
    name: 'Maldives',
    iso3Code: 'MDV',
    flag: '🇲🇻',
    dial: '960',
    currency: 'MVR',
    capital: 'Male',
    continent: 'AS',
    phoneCode: '960',
  },
  {
    isoCode: 'MQ',
    name: 'Martinique',
    iso3Code: 'MTQ',
    flag: '🇲🇶',
    dial: '596',
    currency: 'EUR',
    capital: 'Fort-de-France',
    continent: 'NA',
    phoneCode: '596',
  },
  {
    isoCode: 'MP',
    name: 'Northern Mariana Islands',
    iso3Code: 'MNP',
    flag: '🇲🇵',
    dial: '1-670',
    currency: 'USD',
    capital: 'Saipan',
    continent: 'OC',
    phoneCode: '1-670',
  },
  {
    isoCode: 'MS',
    name: 'Montserrat',
    iso3Code: 'MSR',
    flag: '🇲🇸',
    dial: '1-664',
    currency: 'XCD',
    capital: 'Plymouth',
    continent: 'NA',
    phoneCode: '1-664',
  },
  {
    isoCode: 'MR',
    name: 'Mauritania',
    iso3Code: 'MRT',
    flag: '🇲🇷',
    dial: '222',
    currency: 'MRO',
    capital: 'Nouakchott',
    continent: 'AF',
    phoneCode: '222',
  },
  {
    isoCode: 'IM',
    name: 'Isle of Man',
    iso3Code: 'IMN',
    flag: '🇮🇲',
    dial: '44-1624',
    currency: 'GBP',
    capital: 'Douglas, Isle of Man',
    continent: 'EU',
    phoneCode: '44-1624',
  },
  {
    isoCode: 'UG',
    name: 'Uganda',
    iso3Code: 'UGA',
    flag: '🇺🇬',
    dial: '256',
    currency: 'UGX',
    capital: 'Kampala',
    continent: 'AF',
    phoneCode: '256',
  },
  {
    isoCode: 'TZ',
    name: 'Tanzania',
    iso3Code: 'TZA',
    flag: '🇹🇿',
    dial: '255',
    currency: 'TZS',
    capital: 'Dodoma',
    continent: 'AF',
    phoneCode: '255',
  },
  {
    isoCode: 'MY',
    name: 'Malaysia',
    iso3Code: 'MYS',
    flag: '🇲🇾',
    dial: '60',
    currency: 'MYR',
    capital: 'Kuala Lumpur',
    continent: 'AS',
    phoneCode: '60',
  },
  {
    isoCode: 'MX',
    name: 'Mexico',
    iso3Code: 'MEX',
    flag: '🇲🇽',
    dial: '52',
    currency: 'MXN',
    capital: 'Mexico City',
    continent: 'NA',
    phoneCode: '52',
  },
  {
    isoCode: 'IL',
    name: 'Israel',
    iso3Code: 'ISR',
    flag: '🇮🇱',
    dial: '972',
    currency: 'ILS',
    capital: 'Jerusalem',
    continent: 'AS',
    phoneCode: '972',
  },
  {
    isoCode: 'FR',
    name: 'France',
    iso3Code: 'FRA',
    flag: '🇫🇷',
    dial: '33',
    currency: 'EUR',
    capital: 'Paris',
    continent: 'EU',
    phoneCode: '33',
  },
  {
    isoCode: 'IO',
    name: 'British Indian Ocean Territory',
    iso3Code: 'IOT',
    flag: '🇮🇴',
    dial: '246',
    currency: 'USD',
    capital: 'Diego Garcia',
    continent: 'AS',
    phoneCode: '246',
  },
  {
    isoCode: 'SH',
    name: 'Saint Helena',
    iso3Code: 'SHN',
    flag: '🇸🇭',
    dial: '290',
    currency: 'SHP',
    capital: 'Jamestown',
    continent: 'AF',
    phoneCode: '290',
  },
  {
    isoCode: 'FI',
    name: 'Finland',
    iso3Code: 'FIN',
    flag: '🇫🇮',
    dial: '358',
    currency: 'EUR',
    capital: 'Helsinki',
    continent: 'EU',
    phoneCode: '358',
  },
  {
    isoCode: 'FJ',
    name: 'Fiji',
    iso3Code: 'FJI',
    flag: '🇫🇯',
    dial: '679',
    currency: 'FJD',
    capital: 'Suva',
    continent: 'OC',
    phoneCode: '679',
  },
  {
    isoCode: 'FK',
    name: 'Falkland Islands',
    iso3Code: 'FLK',
    flag: '🇫🇰',
    dial: '500',
    currency: 'FKP',
    capital: 'Stanley',
    continent: 'SA',
    phoneCode: '500',
  },
  {
    isoCode: 'FM',
    name: 'Micronesia',
    iso3Code: 'FSM',
    flag: '🇫🇲',
    dial: '691',
    currency: 'USD',
    capital: 'Palikir',
    continent: 'OC',
    phoneCode: '691',
  },
  {
    isoCode: 'FO',
    name: 'Faroe Islands',
    iso3Code: 'FRO',
    flag: '🇫🇴',
    dial: '298',
    currency: 'DKK',
    capital: 'Torshavn',
    continent: 'EU',
    phoneCode: '298',
  },
  {
    isoCode: 'NI',
    name: 'Nicaragua',
    iso3Code: 'NIC',
    flag: '🇳🇮',
    dial: '505',
    currency: 'NIO',
    capital: 'Managua',
    continent: 'NA',
    phoneCode: '505',
  },
  {
    isoCode: 'NL',
    name: 'Netherlands',
    iso3Code: 'NLD',
    flag: '🇳🇱',
    dial: '31',
    currency: 'EUR',
    capital: 'Amsterdam',
    continent: 'EU',
    phoneCode: '31',
  },
  {
    isoCode: 'NO',
    name: 'Norway',
    iso3Code: 'NOR',
    flag: '🇳🇴',
    dial: '47',
    currency: 'NOK',
    capital: 'Oslo',
    continent: 'EU',
    phoneCode: '47',
  },
  {
    isoCode: 'NA',
    name: 'Namibia',
    iso3Code: 'NAM',
    flag: '🇳🇦',
    dial: '264',
    currency: 'NAD',
    capital: 'Windhoek',
    continent: 'AF',
    phoneCode: '264',
  },
  {
    isoCode: 'VU',
    name: 'Vanuatu',
    iso3Code: 'VUT',
    flag: '🇻🇺',
    dial: '678',
    currency: 'VUV',
    capital: 'Port Vila',
    continent: 'OC',
    phoneCode: '678',
  },
  {
    isoCode: 'NC',
    name: 'New Caledonia',
    iso3Code: 'NCL',
    flag: '🇳🇨',
    dial: '687',
    currency: 'XPF',
    capital: 'Noumea',
    continent: 'OC',
    phoneCode: '687',
  },
  {
    isoCode: 'NE',
    name: 'Niger',
    iso3Code: 'NER',
    flag: '🇳🇪',
    dial: '227',
    currency: 'XOF',
    capital: 'Niamey',
    continent: 'AF',
    phoneCode: '227',
  },
  {
    isoCode: 'NF',
    name: 'Norfolk Island',
    iso3Code: 'NFK',
    flag: '🇳🇫',
    dial: '672',
    currency: 'AUD',
    capital: 'Kingston',
    continent: 'OC',
    phoneCode: '672',
  },
  {
    isoCode: 'NG',
    name: 'Nigeria',
    iso3Code: 'NGA',
    flag: '🇳🇬',
    dial: '234',
    currency: 'NGN',
    capital: 'Abuja',
    continent: 'AF',
    phoneCode: '234',
  },
  {
    isoCode: 'NZ',
    name: 'New Zealand',
    iso3Code: 'NZL',
    flag: '🇳🇿',
    dial: '64',
    currency: 'NZD',
    capital: 'Wellington',
    continent: 'OC',
    phoneCode: '64',
  },
  {
    isoCode: 'NP',
    name: 'Nepal',
    iso3Code: 'NPL',
    flag: '🇳🇵',
    dial: '977',
    currency: 'NPR',
    capital: 'Kathmandu',
    continent: 'AS',
    phoneCode: '977',
  },
  {
    isoCode: 'NR',
    name: 'Nauru',
    iso3Code: 'NRU',
    flag: '🇳🇷',
    dial: '674',
    currency: 'AUD',
    capital: 'Yaren',
    continent: 'OC',
    phoneCode: '674',
  },
  {
    isoCode: 'NU',
    name: 'Niue',
    iso3Code: 'NIU',
    flag: '🇳🇺',
    dial: '683',
    currency: 'NZD',
    capital: 'Alofi',
    continent: 'OC',
    phoneCode: '683',
  },
  {
    isoCode: 'CK',
    name: 'Cook Islands',
    iso3Code: 'COK',
    flag: '🇨🇰',
    dial: '682',
    currency: 'NZD',
    capital: 'Avarua',
    continent: 'OC',
    phoneCode: '682',
  },
  {
    isoCode: 'XK',
    name: 'Kosovo',
    iso3Code: 'XKX',
    flag: '🇽🇰',
    dial: '383',
    currency: 'EUR',
    capital: 'Pristina',
    continent: 'EU',
    phoneCode: '383',
  },
  {
    isoCode: 'CI',
    name: 'Ivory Coast',
    iso3Code: 'CIV',
    flag: '🇨🇮',
    dial: '225',
    currency: 'XOF',
    capital: 'Yamoussoukro',
    continent: 'AF',
    phoneCode: '225',
  },
  {
    isoCode: 'CH',
    name: 'Switzerland',
    iso3Code: 'CHE',
    flag: '🇨🇭',
    dial: '41',
    currency: 'CHF',
    capital: 'Berne',
    continent: 'EU',
    phoneCode: '41',
  },
  {
    isoCode: 'CO',
    name: 'Colombia',
    iso3Code: 'COL',
    flag: '🇨🇴',
    dial: '57',
    currency: 'COP',
    capital: 'Bogota',
    continent: 'SA',
    phoneCode: '57',
  },
  {
    isoCode: 'CN',
    name: 'China',
    iso3Code: 'CHN',
    flag: '🇨🇳',
    dial: '86',
    currency: 'CNY',
    capital: 'Beijing',
    continent: 'AS',
    phoneCode: '86',
  },
  {
    isoCode: 'CM',
    name: 'Cameroon',
    iso3Code: 'CMR',
    flag: '🇨🇲',
    dial: '237',
    currency: 'XAF',
    capital: 'Yaounde',
    continent: 'AF',
    phoneCode: '237',
  },
  {
    isoCode: 'CL',
    name: 'Chile',
    iso3Code: 'CHL',
    flag: '🇨🇱',
    dial: '56',
    currency: 'CLP',
    capital: 'Santiago',
    continent: 'SA',
    phoneCode: '56',
  },
  {
    isoCode: 'CC',
    name: 'Cocos Islands',
    iso3Code: 'CCK',
    flag: '🇨🇨',
    dial: '61',
    currency: 'AUD',
    capital: 'West Island',
    continent: 'AS',
    phoneCode: '61',
  },
  {
    isoCode: 'CA',
    name: 'Canada',
    iso3Code: 'CAN',
    flag: '🇨🇦',
    dial: '1',
    currency: 'CAD',
    capital: 'Ottawa',
    continent: 'NA',
    phoneCode: '1',
  },
  {
    isoCode: 'CG',
    name: 'Republic of the Congo',
    iso3Code: 'COG',
    flag: '🇨🇬',
    dial: '242',
    currency: 'XAF',
    capital: 'Brazzaville',
    continent: 'AF',
    phoneCode: '242',
  },
  {
    isoCode: 'CF',
    name: 'Central African Republic',
    iso3Code: 'CAF',
    flag: '🇨🇫',
    dial: '236',
    currency: 'XAF',
    capital: 'Bangui',
    continent: 'AF',
    phoneCode: '236',
  },
  {
    isoCode: 'CD',
    name: 'Democratic Republic of the Congo',
    iso3Code: 'COD',
    flag: '🇨🇩',
    dial: '243',
    currency: 'CDF',
    capital: 'Kinshasa',
    continent: 'AF',
    phoneCode: '243',
  },
  {
    isoCode: 'CZ',
    name: 'Czech Republic',
    iso3Code: 'CZE',
    flag: '🇨🇿',
    dial: '420',
    currency: 'CZK',
    capital: 'Prague',
    continent: 'EU',
    phoneCode: '420',
  },
  {
    isoCode: 'CY',
    name: 'Cyprus',
    iso3Code: 'CYP',
    flag: '🇨🇾',
    dial: '357',
    currency: 'EUR',
    capital: 'Nicosia',
    continent: 'EU',
    phoneCode: '357',
  },
  {
    isoCode: 'CX',
    name: 'Christmas Island',
    iso3Code: 'CXR',
    flag: '🇨🇽',
    dial: '61',
    currency: 'AUD',
    capital: 'Flying Fish Cove',
    continent: 'AS',
    phoneCode: '61',
  },
  {
    isoCode: 'CR',
    name: 'Costa Rica',
    iso3Code: 'CRI',
    flag: '🇨🇷',
    dial: '506',
    currency: 'CRC',
    capital: 'San Jose',
    continent: 'NA',
    phoneCode: '506',
  },
  {
    isoCode: 'CW',
    name: 'Curacao',
    iso3Code: 'CUW',
    flag: '🇨🇼',
    dial: '599',
    currency: 'ANG',
    capital: ' Willemstad',
    continent: 'NA',
    phoneCode: '599',
  },
  {
    isoCode: 'CV',
    name: 'Cape Verde',
    iso3Code: 'CPV',
    flag: '🇨🇻',
    dial: '238',
    currency: 'CVE',
    capital: 'Praia',
    continent: 'AF',
    phoneCode: '238',
  },
  {
    isoCode: 'CU',
    name: 'Cuba',
    iso3Code: 'CUB',
    flag: '🇨🇺',
    dial: '53',
    currency: 'CUP',
    capital: 'Havana',
    continent: 'NA',
    phoneCode: '53',
  },
  {
    isoCode: 'SZ',
    name: 'Swaziland',
    iso3Code: 'SWZ',
    flag: '🇸🇿',
    dial: '268',
    currency: 'SZL',
    capital: 'Mbabane',
    continent: 'AF',
    phoneCode: '268',
  },
  {
    isoCode: 'SY',
    name: 'Syria',
    iso3Code: 'SYR',
    flag: '🇸🇾',
    dial: '963',
    currency: 'SYP',
    capital: 'Damascus',
    continent: 'AS',
    phoneCode: '963',
  },
  {
    isoCode: 'SX',
    name: 'Sint Maarten',
    iso3Code: 'SXM',
    flag: '🇸🇽',
    dial: '599',
    currency: 'ANG',
    capital: 'Philipsburg',
    continent: 'NA',
    phoneCode: '599',
  },
  {
    isoCode: 'KG',
    name: 'Kyrgyzstan',
    iso3Code: 'KGZ',
    flag: '🇰🇬',
    dial: '996',
    currency: 'KGS',
    capital: 'Bishkek',
    continent: 'AS',
    phoneCode: '996',
  },
  {
    isoCode: 'KE',
    name: 'Kenya',
    iso3Code: 'KEN',
    flag: '🇰🇪',
    dial: '254',
    currency: 'KES',
    capital: 'Nairobi',
    continent: 'AF',
    phoneCode: '254',
  },
  {
    isoCode: 'SS',
    name: 'South Sudan',
    iso3Code: 'SSD',
    flag: '🇸🇸',
    dial: '211',
    currency: 'SSP',
    capital: 'Juba',
    continent: 'AF',
    phoneCode: '211',
  },
  {
    isoCode: 'SR',
    name: 'Suriname',
    iso3Code: 'SUR',
    flag: '🇸🇷',
    dial: '597',
    currency: 'SRD',
    capital: 'Paramaribo',
    continent: 'SA',
    phoneCode: '597',
  },
  {
    isoCode: 'KI',
    name: 'Kiribati',
    iso3Code: 'KIR',
    flag: '🇰🇮',
    dial: '686',
    currency: 'AUD',
    capital: 'Tarawa',
    continent: 'OC',
    phoneCode: '686',
  },
  {
    isoCode: 'KH',
    name: 'Cambodia',
    iso3Code: 'KHM',
    flag: '🇰🇭',
    dial: '855',
    currency: 'KHR',
    capital: 'Phnom Penh',
    continent: 'AS',
    phoneCode: '855',
  },
  {
    isoCode: 'KN',
    name: 'Saint Kitts and Nevis',
    iso3Code: 'KNA',
    flag: '🇰🇳',
    dial: '1-869',
    currency: 'XCD',
    capital: 'Basseterre',
    continent: 'NA',
    phoneCode: '1-869',
  },
  {
    isoCode: 'KM',
    name: 'Comoros',
    iso3Code: 'COM',
    flag: '🇰🇲',
    dial: '269',
    currency: 'KMF',
    capital: 'Moroni',
    continent: 'AF',
    phoneCode: '269',
  },
  {
    isoCode: 'ST',
    name: 'Sao Tome and Principe',
    iso3Code: 'STP',
    flag: '🇸🇹',
    dial: '239',
    currency: 'STD',
    capital: 'Sao Tome',
    continent: 'AF',
    phoneCode: '239',
  },
  {
    isoCode: 'SK',
    name: 'Slovakia',
    iso3Code: 'SVK',
    flag: '🇸🇰',
    dial: '421',
    currency: 'EUR',
    capital: 'Bratislava',
    continent: 'EU',
    phoneCode: '421',
  },
  {
    isoCode: 'KR',
    name: 'South Korea',
    iso3Code: 'KOR',
    flag: '🇰🇷',
    dial: '82',
    currency: 'KRW',
    capital: 'Seoul',
    continent: 'AS',
    phoneCode: '82',
  },
  {
    isoCode: 'SI',
    name: 'Slovenia',
    iso3Code: 'SVN',
    flag: '🇸🇮',
    dial: '386',
    currency: 'EUR',
    capital: 'Ljubljana',
    continent: 'EU',
    phoneCode: '386',
  },
  {
    isoCode: 'KP',
    name: 'North Korea',
    iso3Code: 'PRK',
    flag: '🇰🇵',
    dial: '850',
    currency: 'KPW',
    capital: 'Pyongyang',
    continent: 'AS',
    phoneCode: '850',
  },
  {
    isoCode: 'KW',
    name: 'Kuwait',
    iso3Code: 'KWT',
    flag: '🇰🇼',
    dial: '965',
    currency: 'KWD',
    capital: 'Kuwait City',
    continent: 'AS',
    phoneCode: '965',
  },
  {
    isoCode: 'SN',
    name: 'Senegal',
    iso3Code: 'SEN',
    flag: '🇸🇳',
    dial: '221',
    currency: 'XOF',
    capital: 'Dakar',
    continent: 'AF',
    phoneCode: '221',
  },
  {
    isoCode: 'SM',
    name: 'San Marino',
    iso3Code: 'SMR',
    flag: '🇸🇲',
    dial: '378',
    currency: 'EUR',
    capital: 'San Marino',
    continent: 'EU',
    phoneCode: '378',
  },
  {
    isoCode: 'SL',
    name: 'Sierra Leone',
    iso3Code: 'SLE',
    flag: '🇸🇱',
    dial: '232',
    currency: 'SLL',
    capital: 'Freetown',
    continent: 'AF',
    phoneCode: '232',
  },
  {
    isoCode: 'SC',
    name: 'Seychelles',
    iso3Code: 'SYC',
    flag: '🇸🇨',
    dial: '248',
    currency: 'SCR',
    capital: 'Victoria',
    continent: 'AF',
    phoneCode: '248',
  },
  {
    isoCode: 'KZ',
    name: 'Kazakhstan',
    iso3Code: 'KAZ',
    flag: '🇰🇿',
    dial: '7',
    currency: 'KZT',
    capital: 'Astana',
    continent: 'AS',
    phoneCode: '7',
  },
  {
    isoCode: 'KY',
    name: 'Cayman Islands',
    iso3Code: 'CYM',
    flag: '🇰🇾',
    dial: '1-345',
    currency: 'KYD',
    capital: 'George Town',
    continent: 'NA',
    phoneCode: '1-345',
  },
  {
    isoCode: 'SG',
    name: 'Singapore',
    iso3Code: 'SGP',
    flag: '🇸🇬',
    dial: '65',
    currency: 'SGD',
    capital: 'Singapur',
    continent: 'AS',
    phoneCode: '65',
  },
  {
    isoCode: 'SE',
    name: 'Sweden',
    iso3Code: 'SWE',
    flag: '🇸🇪',
    dial: '46',
    currency: 'SEK',
    capital: 'Stockholm',
    continent: 'EU',
    phoneCode: '46',
  },
  {
    isoCode: 'SD',
    name: 'Sudan',
    iso3Code: 'SDN',
    flag: '🇸🇩',
    dial: '249',
    currency: 'SDG',
    capital: 'Khartoum',
    continent: 'AF',
    phoneCode: '249',
  },
  {
    isoCode: 'DO',
    name: 'Dominican Republic',
    iso3Code: 'DOM',
    flag: '🇩🇴',
    dial: '1-809',
    currency: 'DOP',
    capital: 'Santo Domingo',
    continent: 'NA',
    phoneCode: '1-809',
  },
  {
    isoCode: 'DO',
    name: 'Dominican Republic',
    iso3Code: 'DOM',
    flag: '🇩🇴',
    dial: '1-829',
    currency: 'DOP',
    capital: 'Santo Domingo',
    continent: 'NA',
    phoneCode: '1-829',
  },
  {
    isoCode: 'DM',
    name: 'Dominica',
    iso3Code: 'DMA',
    flag: '🇩🇲',
    dial: '1-767',
    currency: 'XCD',
    capital: 'Roseau',
    continent: 'NA',
    phoneCode: '1-767',
  },
  {
    isoCode: 'DJ',
    name: 'Djibouti',
    iso3Code: 'DJI',
    flag: '🇩🇯',
    dial: '253',
    currency: 'DJF',
    capital: 'Djibouti',
    continent: 'AF',
    phoneCode: '253',
  },
  {
    isoCode: 'DK',
    name: 'Denmark',
    iso3Code: 'DNK',
    flag: '🇩🇰',
    dial: '45',
    currency: 'DKK',
    capital: 'Copenhagen',
    continent: 'EU',
    phoneCode: '45',
  },
  {
    isoCode: 'VG',
    name: 'British Virgin Islands',
    iso3Code: 'VGB',
    flag: '🇻🇬',
    dial: '1-284',
    currency: 'USD',
    capital: 'Road Town',
    continent: 'NA',
    phoneCode: '1-284',
  },
  {
    isoCode: 'DE',
    name: 'Germany',
    iso3Code: 'DEU',
    flag: '🇩🇪',
    dial: '49',
    currency: 'EUR',
    capital: 'Berlin',
    continent: 'EU',
    phoneCode: '49',
  },
  {
    isoCode: 'YE',
    name: 'Yemen',
    iso3Code: 'YEM',
    flag: '🇾🇪',
    dial: '967',
    currency: 'YER',
    capital: 'Sanaa',
    continent: 'AS',
    phoneCode: '967',
  },
  {
    isoCode: 'DZ',
    name: 'Algeria',
    iso3Code: 'DZA',
    flag: '🇩🇿',
    dial: '213',
    currency: 'DZD',
    capital: 'Algiers',
    continent: 'AF',
    phoneCode: '213',
  },
  {
    isoCode: 'UY',
    name: 'Uruguay',
    iso3Code: 'URY',
    flag: '🇺🇾',
    dial: '598',
    currency: 'UYU',
    capital: 'Montevideo',
    continent: 'SA',
    phoneCode: '598',
  },
  {
    isoCode: 'YT',
    name: 'Mayotte',
    iso3Code: 'MYT',
    flag: '🇾🇹',
    dial: '262',
    currency: 'EUR',
    capital: 'Mamoudzou',
    continent: 'AF',
    phoneCode: '262',
  },
  {
    isoCode: 'UM',
    name: 'United States Minor Outlying Islands',
    iso3Code: 'UMI',
    flag: '🇺🇲',
    dial: '1',
    currency: 'USD',
    capital: '',
    continent: 'OC',
    phoneCode: '1',
  },
  {
    isoCode: 'LB',
    name: 'Lebanon',
    iso3Code: 'LBN',
    flag: '🇱🇧',
    dial: '961',
    currency: 'LBP',
    capital: 'Beirut',
    continent: 'AS',
    phoneCode: '961',
  },
  {
    isoCode: 'LC',
    name: 'Saint Lucia',
    iso3Code: 'LCA',
    flag: '🇱🇨',
    dial: '1-758',
    currency: 'XCD',
    capital: 'Castries',
    continent: 'NA',
    phoneCode: '1-758',
  },
  {
    isoCode: 'LA',
    name: 'Laos',
    iso3Code: 'LAO',
    flag: '🇱🇦',
    dial: '856',
    currency: 'LAK',
    capital: 'Vientiane',
    continent: 'AS',
    phoneCode: '856',
  },
  {
    isoCode: 'TV',
    name: 'Tuvalu',
    iso3Code: 'TUV',
    flag: '🇹🇻',
    dial: '688',
    currency: 'AUD',
    capital: 'Funafuti',
    continent: 'OC',
    phoneCode: '688',
  },
  {
    isoCode: 'TW',
    name: 'Taiwan',
    iso3Code: 'TWN',
    flag: '🇹🇼',
    dial: '886',
    currency: 'TWD',
    capital: 'Taipei',
    continent: 'AS',
    phoneCode: '886',
  },
  {
    isoCode: 'TT',
    name: 'Trinidad and Tobago',
    iso3Code: 'TTO',
    flag: '🇹🇹',
    dial: '1-868',
    currency: 'TTD',
    capital: 'Port of Spain',
    continent: 'NA',
    phoneCode: '1-868',
  },
  {
    isoCode: 'TR',
    name: 'Turkey',
    iso3Code: 'TUR',
    flag: '🇹🇷',
    dial: '90',
    currency: 'TRY',
    capital: 'Ankara',
    continent: 'AS',
    phoneCode: '90',
  },
  {
    isoCode: 'LK',
    name: 'Sri Lanka',
    iso3Code: 'LKA',
    flag: '🇱🇰',
    dial: '94',
    currency: 'LKR',
    capital: 'Colombo',
    continent: 'AS',
    phoneCode: '94',
  },
  {
    isoCode: 'LI',
    name: 'Liechtenstein',
    iso3Code: 'LIE',
    flag: '🇱🇮',
    dial: '423',
    currency: 'CHF',
    capital: 'Vaduz',
    continent: 'EU',
    phoneCode: '423',
  },
  {
    isoCode: 'LV',
    name: 'Latvia',
    iso3Code: 'LVA',
    flag: '🇱🇻',
    dial: '371',
    currency: 'EUR',
    capital: 'Riga',
    continent: 'EU',
    phoneCode: '371',
  },
  {
    isoCode: 'TO',
    name: 'Tonga',
    iso3Code: 'TON',
    flag: '🇹🇴',
    dial: '676',
    currency: 'TOP',
    capital: "Nuku'alofa",
    continent: 'OC',
    phoneCode: '676',
  },
  {
    isoCode: 'LT',
    name: 'Lithuania',
    iso3Code: 'LTU',
    flag: '🇱🇹',
    dial: '370',
    currency: 'LTL',
    capital: 'Vilnius',
    continent: 'EU',
    phoneCode: '370',
  },
  {
    isoCode: 'LU',
    name: 'Luxembourg',
    iso3Code: 'LUX',
    flag: '🇱🇺',
    dial: '352',
    currency: 'EUR',
    capital: 'Luxembourg',
    continent: 'EU',
    phoneCode: '352',
  },
  {
    isoCode: 'LR',
    name: 'Liberia',
    iso3Code: 'LBR',
    flag: '🇱🇷',
    dial: '231',
    currency: 'LRD',
    capital: 'Monrovia',
    continent: 'AF',
    phoneCode: '231',
  },
  {
    isoCode: 'LS',
    name: 'Lesotho',
    iso3Code: 'LSO',
    flag: '🇱🇸',
    dial: '266',
    currency: 'LSL',
    capital: 'Maseru',
    continent: 'AF',
    phoneCode: '266',
  },
  {
    isoCode: 'TH',
    name: 'Thailand',
    iso3Code: 'THA',
    flag: '🇹🇭',
    dial: '66',
    currency: 'THB',
    capital: 'Bangkok',
    continent: 'AS',
    phoneCode: '66',
  },
  {
    isoCode: 'TF',
    name: 'French Southern Territories',
    iso3Code: 'ATF',
    flag: '🇹🇫',
    dial: '262',
    currency: 'EUR',
    capital: 'Port-aux-Francais',
    continent: 'AN',
    phoneCode: '262',
  },
  {
    isoCode: 'TG',
    name: 'Togo',
    iso3Code: 'TGO',
    flag: '🇹🇬',
    dial: '228',
    currency: 'XOF',
    capital: 'Lome',
    continent: 'AF',
    phoneCode: '228',
  },
  {
    isoCode: 'TD',
    name: 'Chad',
    iso3Code: 'TCD',
    flag: '🇹🇩',
    dial: '235',
    currency: 'XAF',
    capital: "N'Djamena",
    continent: 'AF',
    phoneCode: '235',
  },
  {
    isoCode: 'TC',
    name: 'Turks and Caicos Islands',
    iso3Code: 'TCA',
    flag: '🇹🇨',
    dial: '1-649',
    currency: 'USD',
    capital: 'Cockburn Town',
    continent: 'NA',
    phoneCode: '1-649',
  },
  {
    isoCode: 'LY',
    name: 'Libya',
    iso3Code: 'LBY',
    flag: '🇱🇾',
    dial: '218',
    currency: 'LYD',
    capital: 'Tripolis',
    continent: 'AF',
    phoneCode: '218',
  },
  {
    isoCode: 'VA',
    name: 'Vatican',
    iso3Code: 'VAT',
    flag: '🇻🇦',
    dial: '379',
    currency: 'EUR',
    capital: 'Vatican City',
    continent: 'EU',
    phoneCode: '379',
  },
  {
    isoCode: 'VC',
    name: 'Saint Vincent and the Grenadines',
    iso3Code: 'VCT',
    flag: '🇻🇨',
    dial: '1-784',
    currency: 'XCD',
    capital: 'Kingstown',
    continent: 'NA',
    phoneCode: '1-784',
  },
  {
    isoCode: 'AE',
    name: 'United Arab Emirates',
    iso3Code: 'ARE',
    flag: '🇦🇪',
    dial: '971',
    currency: 'AED',
    capital: 'Abu Dhabi',
    continent: 'AS',
    phoneCode: '971',
  },
  {
    isoCode: 'AD',
    name: 'Andorra',
    iso3Code: 'AND',
    flag: '🇦🇩',
    dial: '376',
    currency: 'EUR',
    capital: 'Andorra la Vella',
    continent: 'EU',
    phoneCode: '376',
  },
  {
    isoCode: 'AG',
    name: 'Antigua and Barbuda',
    iso3Code: 'ATG',
    flag: '🇦🇬',
    dial: '1-268',
    currency: 'XCD',
    capital: "St. John's",
    continent: 'NA',
    phoneCode: '1-268',
  },
  {
    isoCode: 'AF',
    name: 'Afghanistan',
    iso3Code: 'AFG',
    flag: '🇦🇫',
    dial: '93',
    currency: 'AFN',
    capital: 'Kabul',
    continent: 'AS',
    phoneCode: '93',
  },
  {
    isoCode: 'AI',
    name: 'Anguilla',
    iso3Code: 'AIA',
    flag: '🇦🇮',
    dial: '1-264',
    currency: 'XCD',
    capital: 'The Valley',
    continent: 'NA',
    phoneCode: '1-264',
  },
  {
    isoCode: 'VI',
    name: 'U.S. Virgin Islands',
    iso3Code: 'VIR',
    flag: '🇻🇮',
    dial: '1-340',
    currency: 'USD',
    capital: 'Charlotte Amalie',
    continent: 'NA',
    phoneCode: '1-340',
  },
  {
    isoCode: 'IS',
    name: 'Iceland',
    iso3Code: 'ISL',
    flag: '🇮🇸',
    dial: '354',
    currency: 'ISK',
    capital: 'Reykjavik',
    continent: 'EU',
    phoneCode: '354',
  },
  {
    isoCode: 'IR',
    name: 'Iran',
    iso3Code: 'IRN',
    flag: '🇮🇷',
    dial: '98',
    currency: 'IRR',
    capital: 'Tehran',
    continent: 'AS',
    phoneCode: '98',
  },
  {
    isoCode: 'AM',
    name: 'Armenia',
    iso3Code: 'ARM',
    flag: '🇦🇲',
    dial: '374',
    currency: 'AMD',
    capital: 'Yerevan',
    continent: 'AS',
    phoneCode: '374',
  },
  {
    isoCode: 'AL',
    name: 'Albania',
    iso3Code: 'ALB',
    flag: '🇦🇱',
    dial: '355',
    currency: 'ALL',
    capital: 'Tirana',
    continent: 'EU',
    phoneCode: '355',
  },
  {
    isoCode: 'AO',
    name: 'Angola',
    iso3Code: 'AGO',
    flag: '🇦🇴',
    dial: '244',
    currency: 'AOA',
    capital: 'Luanda',
    continent: 'AF',
    phoneCode: '244',
  },
  {
    isoCode: 'AQ',
    name: 'Antarctica',
    iso3Code: 'ATA',
    flag: '🇦🇶',
    dial: '672',
    currency: '',
    capital: '',
    continent: 'AN',
    phoneCode: '672',
  },
  {
    isoCode: 'AS',
    name: 'American Samoa',
    iso3Code: 'ASM',
    flag: '🇦🇸',
    dial: '1-684',
    currency: 'USD',
    capital: 'Pago Pago',
    continent: 'OC',
    phoneCode: '1-684',
  },
  {
    isoCode: 'AR',
    name: 'Argentina',
    iso3Code: 'ARG',
    flag: '🇦🇷',
    dial: '54',
    currency: 'ARS',
    capital: 'Buenos Aires',
    continent: 'SA',
    phoneCode: '54',
  },
  {
    isoCode: 'AU',
    name: 'Australia',
    iso3Code: 'AUS',
    flag: '🇦🇺',
    dial: '61',
    currency: 'AUD',
    capital: 'Canberra',
    continent: 'OC',
    phoneCode: '61',
  },
  {
    isoCode: 'AT',
    name: 'Austria',
    iso3Code: 'AUT',
    flag: '🇦🇹',
    dial: '43',
    currency: 'EUR',
    capital: 'Vienna',
    continent: 'EU',
    phoneCode: '43',
  },
  {
    isoCode: 'AW',
    name: 'Aruba',
    iso3Code: 'ABW',
    flag: '🇦🇼',
    dial: '297',
    currency: 'AWG',
    capital: 'Oranjestad',
    continent: 'NA',
    phoneCode: '297',
  },
  {
    isoCode: 'IN',
    name: 'India',
    iso3Code: 'IND',
    flag: '🇮🇳',
    dial: '91',
    currency: 'INR',
    capital: 'New Delhi',
    continent: 'AS',
    phoneCode: '91',
  },
  {
    isoCode: 'AX',
    name: 'Aland Islands',
    iso3Code: 'ALA',
    flag: '🇦🇽',
    dial: '358-18',
    currency: 'EUR',
    capital: 'Mariehamn',
    continent: 'EU',
    phoneCode: '358-18',
  },
  {
    isoCode: 'AZ',
    name: 'Azerbaijan',
    iso3Code: 'AZE',
    flag: '🇦🇿',
    dial: '994',
    currency: 'AZN',
    capital: 'Baku',
    continent: 'AS',
    phoneCode: '994',
  },
  {
    isoCode: 'IE',
    name: 'Ireland',
    iso3Code: 'IRL',
    flag: '🇮🇪',
    dial: '353',
    currency: 'EUR',
    capital: 'Dublin',
    continent: 'EU',
    phoneCode: '353',
  },
  {
    isoCode: 'ID',
    name: 'Indonesia',
    iso3Code: 'IDN',
    flag: '🇮🇩',
    dial: '62',
    currency: 'IDR',
    capital: 'Jakarta',
    continent: 'AS',
    phoneCode: '62',
  },
  {
    isoCode: 'UA',
    name: 'Ukraine',
    iso3Code: 'UKR',
    flag: '🇺🇦',
    dial: '380',
    currency: 'UAH',
    capital: 'Kiev',
    continent: 'EU',
    phoneCode: '380',
  },
  {
    isoCode: 'QA',
    name: 'Qatar',
    iso3Code: 'QAT',
    flag: '🇶🇦',
    dial: '974',
    currency: 'QAR',
    capital: 'Doha',
    continent: 'AS',
    phoneCode: '974',
  },
  {
    isoCode: 'MZ',
    name: 'Mozambique',
    iso3Code: 'MOZ',
    flag: '🇲🇿',
    dial: '258',
    currency: 'MZN',
    capital: 'Maputo',
    continent: 'AF',
    phoneCode: '258',
  },
];

export const defaultCountry = countryList.find(
  (country) => country.isoCode === 'US' && country.phoneCode === '1'
) as Country;
